MT#9407 Add defaults support to elasticsearch-remove-old-indices
We should abort the script in case of missed NGCP config,
otherwise we can accidentally remove customer's index 'logstash'

Change-Id: I45287440f03e5e5aa7310b149b2a6bfe70307c52

diff --git a/elasticsearch-remove-old-indices b/elasticsearch-remove-old-indices
--- a/elasticsearch-remove-old-indices
+++ b/elasticsearch-remove-old-indices
@@ -53,6 +53,15 @@ EOF
 ELASTICSEARCH="http://localhost:9200"
 KEEP=14
 GREP="logstash"
+DEFAULTS="/etc/default/ngcp-elasticsearch-cleanup"
+
+# Load startup options if available
+if [ -f $DEFAULTS ]; then
+  . $DEFAULTS
+else
+  echo "Missed NGCP default config, aborting" >&2
+  exit 1
+fi
 
 # Validate numeric values
 RE_D="^[0-9]+$"
